paths:
  '.github/workflows/**/*.{yml,yaml}':
    ignore:
      # actionlint does not yet recognize GitHub's $/ self-repository syntax: https://github.com/rhysd/actionlint/issues/711
      - '^specifying action "\$/[^\"]+" in invalid format because ref is missing'
      - '^reusable workflow call "\$/.+" at "uses" is not following the format'
