/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiCentrifugoConnectRouteImport } from './routes/api/centrifugo.connect'
import { Route as ApiUploadsIdRouteImport } from './routes/api/uploads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCentrifugoConnectRoute = ApiCentrifugoConnectRouteImport.update({
  id: '/api/centrifugo/connect',
  path: '/api/centrifugo/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUploadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/centrifugo/connect': typeof ApiCentrifugoConnectRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/centrifugo/connect': typeof ApiCentrifugoConnectRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/centrifugo/connect': typeof ApiCentrifugoConnectRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/uploads'
    | '/api/centrifugo/connect'
    | '/api/uploads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/uploads'
    | '/api/centrifugo/connect'
    | '/api/uploads/$id'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/uploads'
    | '/api/centrifugo/connect'
    | '/api/uploads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiCentrifugoConnectRoute: typeof ApiCentrifugoConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/centrifugo/connect': {
      id: '/api/centrifugo/connect'
      path: '/api/centrifugo/connect'
      fullPath: '/api/centrifugo/connect'
      preLoaderRoute: typeof ApiCentrifugoConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
  }
}

interface ApiUploadsRouteChildren {
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsIdRoute: ApiUploadsIdRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiCentrifugoConnectRoute: ApiCentrifugoConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
